### ISSUE TITLE
Error with `Server.poll` in tick()

### ISSUE THREAD

**Issue by juandpr** [Wolftein/Aurora.Network#5]
Hello, we are implementing Aurora Network, following this repo: https://github.com/ao-org/argentum20-server/blob/master/Codigo/modNetwork.bas#L32

We are encountering an issue with `Server.poll` in this line:

```
Public Sub Tick(ByVal Delta As Single)
    Time(0) = Time(0) + Delta
    Time(1) = Time(1) + Delta
    
    If (Time(0) >= TIME_RECV_FREQUENCY) Then
        Time(0) = 0
        
        Call Server.Poll
    End If
        
    If (Time(1) >= TIME_SEND_FREQUENCY) Then
        Time(1) = 0
        
        Call Server.Flush
    End If
End Sub
```

The error happens on the first `Call Server.Poll` but we don't have much information about the error itself:

```
Error: 91
Descripcion: Variable de tipo Object o la variable de bloque With no está establecida
```

That happens on the first call of the "Tick" method. Do you have any clue?

Thanks in advance.

**Comment by Wolftein** [comment]
Hello, "**Error: 91**" is a generic VBA error indicating that an object has not been initialized. You should call **modNetwork.Listen(ByVal Limit As Long, ByVal Address As String, ByVal Service As String)** before trying to use it.

**Comment by juandpr** [comment]
Thanks, I was able to solve it. There was an issue with the way I was referencing the library
